[package]
name = "sass-rs"
version = "0.0.17"
authors = ["Marius Seritan <github@seritan.net>"]
keywords = ["sass", "ffi"]
description = "Higher level binding for the Sass library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/compass-rs/sass-rs.git"
homepage = "https://github.com/compass-rs/sass-rs"
documentation = "http://compass-rs.github.io/sass-rs/"


[lib]
name = "sass_rs"
path = "src/lib.rs"

[dependencies]
sass-sys = "0"
libc = "0.1"
